version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    network_mode: "host"
    volumes:
      - ./mysql:/data
      - ./mysqlscript/:/docker-entrypoint-initdb.d/